name: Build and Package Blazor WASM App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'   # Adjust the version as needed

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Application
        run: dotnet build --configuration Release --no-restore

      - name: Publish the Blazor WASM App
        run: dotnet publish -c Release -o ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-wasm-app
          path: ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: blazor-wasm-app
        path: ./artifact

    - name: List Artifact Contents
      run: ls -R ./artifact

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: prodcogniapp          # Replace with your Azure App Service name if different
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./artifact

    
